apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 1m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  valuesFrom:
  - kind: ConfigMap
    name: helmvalue
  chart:
    spec:
      chart: falcosecurity/falco
      version: 3.1.1
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: tanzu-helm-resources
      interval: 1m


